name: Get Oakland weekly crime reports

# Set to update at 11 a.m. Monday; if files don't post, manually run later
on:
  schedule:
    - cron: '0 14 * * 1'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  render:
    name: Fetch six Oakland weekly PDFs
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: Rscript -e 'install.packages(c("stringr","tidyverse","rvest"))'
      - name: Get weekly PDFs
        run: Rscript scripts/automate_download_loop_recent.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New crime data collected' || echo "No changes"
          git push origin || echo "No changes to commit"
        
