name: Get Oakland police area map

# Set to update once a year
on:
  schedule:
    - cron: '0 0 1 1 *'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  render:
    name: run code
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install gdal
        run: |
          brew install gdal
      - name: Install packages
        run: Rscript -e 'install.packages(c("janitor","tidyverse","tidycensus","leaflet","leaflet.extras","leaflet.providers","sp","sf","tigris"))'
      - name: Run script
        run: Rscript scripts/process_oakland_districts_map.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New crime data collected' || echo "No changes"
          git push origin || echo "No changes to commit"
